// src/lib/gemini.js
// Gemini generateContent call with a timeout + one retry. Pure: fetch is injectable.

/**
 * @param {{
 *   apiKey: string,
 *   model: string,
 *   prompt: string,
 *   systemInstruction?: string,
 *   fetchImpl?: typeof fetch,
 *   timeoutMs?: number,
 *   retryDelayMs?: number,
 * }} opts
 * @returns {Promise<string>}
 */
export async function requestGemini(opts) {
  const {
    apiKey, model, prompt, systemInstruction = '',
    fetchImpl = (typeof fetch !== 'undefined' ? fetch : null),
    timeoutMs = 12000, retryDelayMs = 1500,
  } = opts;
  if (!apiKey) throw new Error('NO_API_KEY');
  if (!fetchImpl) throw new Error('NO_FETCH');

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(apiKey)}`;
  const body = { contents: [{ role: 'user', parts: [{ text: prompt }] }] };
  if (systemInstruction) body.systemInstruction = { parts: [{ text: systemInstruction }] };

  const attempt = async () => {
    const ac = new AbortController();
    const timer = setTimeout(() => ac.abort(), timeoutMs);
    try {
      return await fetchImpl(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
        signal: ac.signal,
      });
    } finally {
      clearTimeout(timer);
    }
  };

  let res;
  try {
    res = await attempt();
  } catch (e) {
    if (e && e.name === 'AbortError') throw new Error('GEMINI_TIMEOUT');
    throw e;
  }
  if (!res.ok && (res.status === 429 || res.status >= 500)) {
    await new Promise((r) => setTimeout(r, retryDelayMs));
    try {
      res = await attempt();
    } catch (e) {
      if (e && e.name === 'AbortError') throw new Error('GEMINI_TIMEOUT');
      throw e;
    }
  }
  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || `Gemini API returned status ${res.status}`);
  }
  const data = await res.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error('No response generated by Gemini.');
  return text.trim();
}
